const config = require('./utils/config')
const express = require('express')
require('express-async-errors')
const app = express()
const cors = require('cors')
const stationsRouter = require('./controllers/stations')
const stationSeeder = require('./utils/stationsSeeder')
const middleware = require('./utils/middleware')
const mongoose = require('mongoose')

mongoose.connect(config.MONGODB_URI)
stationSeeder.seed()
app.use(cors())
app.use(express.json())
app.use(middleware.requestLogger)
app.use('/api/stations', stationsRouter)
app.use(middleware.unknownEndpoint)
app.use(middleware.errorHandler)

module.exports = app